// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaomqmqybxhuqtugbcmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhb21xbXF5YnhodXF0dWdiY211Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDcyNzUsImV4cCI6MjA3MjU4MzI3NX0.UKBHyiVJ0Ly_EOqoQiOoG49tSaPw5GB7vrQO9waYpvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});